version: 2.1

jobs:
  native-build:
    docker:
      - image: debian:buster-slim
    steps:
      - run: >-
          apt-get update
      - run: >-
          apt-get install -y --no-install-recommends
          ca-certificates git
      - run: >-
          apt-get install -y --no-install-recommends
          autoconf automake make libtool pkg-config
      - run: >-
          apt-get install -y --no-install-recommends
          gcc libc6-dev
      - checkout
      - run: >-
          ./bootstrap
      - run: >-
          ./configure --prefix=/usr/local --disable-shared --without-libpng
      - run: >-
          make -j $(nproc)
      - run: >-
          make install
  arm64-build:
    docker:
      - image: debian:buster-slim
    steps:
      - run: >-
          dpkg --add-architecture arm64
      - run: >-
          apt-get update
      - run: >-
          apt-get install -y --no-install-recommends
          ca-certificates git
      - run: >-
          apt-get install -y --no-install-recommends
          autoconf automake make libtool pkg-config
      - run: >-
          apt-get install -y --no-install-recommends
          gcc-aarch64-linux-gnu libc6-dev:arm64
      - checkout
      - run: >-
          ./bootstrap
      - run: >-
          ./configure --prefix=/usr/local --disable-shared --without-libpng
          --host=aarch64-linux-gnu
      - run: >-
          make -j $(nproc)
      - run: >-
          make install

workflows:
  version: 2
  build:
    jobs:
      - native-build
      - arm64-build
